### ISSUE TITLE
cfg defender on windows 11 issue

### ISSUE THREAD

**Issue by insanowsky** [AndyFul/ConfigureDefender#15]
it seems like "check security logs" isn't working properly on windows 11 (tested on 22449.1000) instead it shows random strings of letters and numbers (maybe encrypted?)
![image](https://user-images.githubusercontent.com/85366281/132034810-567ceb3a-fa99-4f7c-956c-7607f858c213.png)

**Comment by AndyFul** [comment]
This issue is related to the stable version 5.1.1.2 and has been corrected in the beta version 6.0.0.0.
