### ISSUE TITLE
possible to work with server 2016/2019?

### ISSUE THREAD

**Issue by morch-uk** [AndyFul/ConfigureDefender#19]
I was just wondering if it can work Server 2016/2019 as i use one in a standalone capacity? I can make most of the changes in an manual way, could this make those changes more quick for me?

**Comment by AndyFul** [comment]
ConfigureDefender uses PowerShell cmdlets to apply Defender's settings, so this should work on any machine that allows ASR rules, including Windows Server 2016/2019:
https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction?view=o365-worldwide

Anyway, if you are using many machines with the same config, then it will be quicker to do this by GPO, export the settings and apply the exported config to other machines.

There are also PowerShell scripts available. You can modify them and apply them to all machines.

**Comment by morch-uk** [comment]
thanks for the reply, the program says it "only works on windows 10" when i tested it

**Comment by AndyFul** [comment]
After some tests, I decided to support Windows Server. The upcoming version of ConfigureDefender will work for Windows 10 build 1809 or Windows Server 2019, and higher versions.

**Comment by AndyFul** [comment]
The current version supports Windows Server 2019+.
