### ISSUE TITLE
Retrieve current config and display

### ISSUE THREAD

**Issue by ivandretvic** [AndyFul/ConfigureDefender#20]
When opening the tool, it doesn't add the current config to the individual settings. 

**Desired state:**
Open tool.
It retrieves current configuration of system and updates all fields/exceptions/etc
Changes made after the initial load are reflected in system.

This would make it easy to troubleshoot certain settings on an existing config (provided by MDM policy)

Currently, opening the app does not read the current configuration state, represented by Get-MPPreferences command

**Comment by AndyFul** [comment]
If ConfigureDefender works properly then it reads the current settings and reflects them in the application Window.
If it does not work in this way then something prevents ConfigureDefender to read the information from the Windows Registry. ConfigureDefender uses PowerShell cmdlet Get-MPPreferences to gather the current settings.
