### ISSUE TITLE
Trojan.Autoit.Wirus Report

### ISSUE THREAD

**Issue by basteyy** [AndyFul/ConfigureDefender#22]
According to [virustotal](https://www.virustotal.com/gui/file/ac6e97715d22a5c6e747ef5a3f27e3b2a13d68491b4ed52d13b85bb75b1b3bef/detection) the current version contains a Malware Heuristic 1003 similar to Trojan.Autoit.Wirus. 

What could that be?

**Comment by AndyFul** [comment]
False positive. 
I send the executables for whitelisting to Avast, Microsoft Defender, Bitdefender, Norton.

**Comment by basteyy** [comment]
Please close it, as soon it's checked
