### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by WinWeirdo** [AndyFul/ConfigureDefender#23]
can you reprogram it to check defender and other stuff by cmd not powershell, my powershell doesn't work and won't work, so program doesn't work.
![Zrzut ekranu (8)](https://user-images.githubusercontent.com/109212491/179073212-37b03565-7d22-43d8-97f1-da13c3f6202d.png)

**Comment by AndyFul** [comment]
I am afraid that I cannot. ConfigureDefender uses PowerShell native cmdlets to be the most compatible with Windows and Defender.
