### ISSUE TITLE
Use GitHub repo for source code, GitHub Releases for binaries

### ISSUE THREAD

**Issue by szepeviktor** [AndyFul/ConfigureDefender#24]
Hello @AndyFul!

Thank you for your software!
Have you thought about committing the source code to this repository, tagging releases,
and uploading `.exe` files to GitHub Releases?

**Comment by szepeviktor** [comment]
I've tries my best: https://github.com/szepeviktor/ConfigureDefender 👀

**Comment by AndyFul** [comment]
This repository is for the standalone installer made by NSISS from executables that belong to Hard_Configurator project. It is not an independent project.  I do not plan to change it so far.

**Comment by szepeviktor** [comment]
Okay.

Maybe you will change your main repo in the future ...
