### ISSUE TITLE
"Automatic sample submission" repeated warning

### ISSUE THREAD

**Issue by Gittyperson** [AndyFul/ConfigureDefender#26]
Thank you for ConfigureDefender.

Anyone knows of a working fix/solution for Windows' warning/notification (yellow tray icon) when "Automatic sample submission" is set to Off or Prompt?

Pressing 'Dismiss' only clears it temporarily. The warning will usually come back after a mere PC restart.

(using Windows 10)

**Comment by AndyFul** [comment]
Unrelated to ConfigureDefender.
