### ISSUE TITLE
Scrolling the GUI

### ISSUE THREAD

**Issue by ludamo** [AndyFul/ConfigureDefender#28]
Thanks for making this handy program. Is it possible to add a GUIRegisterMsg for WM_MOUSEWHEEL as the GUI doesn't scroll with my mouse in default mode. If I send it WM_VSCROLL messages it will scroll but also it can scroll the comboboxes if one is not careful where the pointer is. Thanks again.

**Comment by AndyFul** [comment]
Thanks. I will add the scroll support in the next version.

**Comment by AndyFul** [comment]
The scrolling was added in July 2024.
