### ISSUE TITLE
Where are the sources ?

### ISSUE THREAD

**Issue by crile** [AndyFul/ConfigureDefender#3]

**Comment by CHEF-KOCH** [comment]
bumper!

**Comment by AndyFul** [comment]
Sorry. The sources of ConfigureDefender can be found in Hard_Configurator sources. ConfigureDefender is a part of Hard_Configurator.
https://github.com/AndyFul/Hard_Configurator---old-versions/blob/master/Hard_Configurator.zip

**Comment by hmnd** [comment]
@AndyFul I'd suggest perhaps adding a link to the source in this repo's README? Without knowing about Hard_Configurator, it's unclear where to get the source.

**Comment by AndyFul** [comment]
OK.

**Comment by AndyFul** [comment]
The link to sources added in the README.md
