### ISSUE TITLE
RemoteIpMoProxyConfigDefender1.0LocalHost

### ISSUE THREAD

**Issue by 26zl** [AndyFul/ConfigureDefender#31]
Hi! First of all, i love your work and this program has helped keeping my PC secure! Thanks for that!

Question: I was wondering what this is: "RemoteIpMoProxyConfigDefender1.0LocalHost" ? It keeps spawning in %temp% even when i clear it. Whats its function? 

Sorry if its a dumb question!

Thanks again!

**Comment by AndyFul** [comment]
No idea. The term ConfigDefender is unrelated to ConfigureDefender. It can be related to some configuration of Proxy server.
