### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by bigstevo** [AndyFul/ConfigureDefender#33]
Being annoying with this one im sure. Lmao

Windows Defender settings are stored in the Windows Registry and most of them are not available **form** Windows Defender Security Center. They can be managed via:

Probably should be "from"

**Comment by AndyFul** [comment]
I am not sure.
The settings can be managed from the Group Policy Management Console. But doing it "from Registry" or "from PowerShell CmdLets" looks awkward. Anyway, I made some corrections. Are they OK?

**Comment by bigstevo** [comment]
yeah looks great lol!
