### ISSUE TITLE
Run from commandline

### ISSUE THREAD

**Issue by dinger1986** [AndyFul/ConfigureDefender#9]
Is there a way to run this from commandline? 

IE run configuredefender.exe /high

If not is there some way it could be done?

Daniel

**Comment by AndyFul** [comment]
No, I am afraid. I intentionally made it without commandline support.

**Comment by dinger1986** [comment]
ok, is there any quick commands you know or powershell command to do similar things? so we can batch it up? I can research it but was hoping there would be an easier way

**Comment by AndyFul** [comment]
There are some PowerShell scripts available, but I have seen them several months ago so I cannot post you the links.

**Comment by dinger1986** [comment]
no problems, I was hoping you might have the commands somewhere in your source and I could have grabbed them. Appreciate your time both with this and development of this helpful tool, I very much like Configure Defender and will continue using it.

**Comment by AndyFul** [comment]
You can grab the commands from the source files:
https://github.com/AndyFul/Hard_Configurator/tree/master/src/Hard_Configurator/ConfigureDefender

Please learn first what they do:
https://docs.microsoft.com/en-us/powershell/module/defender/?view=win10-ps

**Comment by dinger1986** [comment]
yeah ill check them before doing anything, thanks!
